### ISSUE TITLE
interfaces types aren't included

### ISSUE THREAD

**Issue by WilcoSp** [KartikeSingh/ms-prettify#6]
the interface types which contain the option typings isn't included with npm, this most likely because typescript doesn't include already existing d.ts files. changing it to a .ts file should be enough

**Comment by WilcoSp** [comment]
I also noticed that the export of default is as a value (like timer) and not the actual default 

I may fork this project and sort out the typings & exports

**Comment by KartikeSingh** [comment]
shit i never noticed the issue, will fix this

**Comment by KartikeSingh** [comment]
Hey @WilcoSp
My apologies, I am not sure if I fixed it before but just now I made a new release (1.5.0) it is for sure exporting all the types.
If you still have any issue feel free to let us know
