### ISSUE TITLE
Replacing of 'milliseconds' -> 'ms' goes wrong

### ISSUE THREAD

**Issue by wouteroonk** [KartikeSingh/ms-prettify#7]
The `millisecond` must be replaced with `ms` first, before replacing `second`. 
This prevents conflicts during the replacement process, since `second` is also a substring of `millisecond`.

toTimeString.ts
```
if (!expanded)
  time = time
    .replace(/millisecond+s?/, 'ms')
    .replace(/(year|day|hour|minute|second|week)s?/g, (x) => x[0])
```

**Comment by KartikeSingh** [comment]
hey that does make sense, if you want you can create a PR for it.
thanks a lot for notifying me about it!

**Comment by KartikeSingh** [comment]
Hey I have fixed it, if you encounter any issues feel free to let me know!

[release](https://www.npmjs.com/package/ms-prettify/v/1.5.1)
